//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public int id { get; set; }
        public string idAuto { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public string Price { get; set; }
        public string Number { get; set; }
        public string Release { get; set; }
    
        public virtual main main { get; set; }
    }
}
